from assets.styles import (COLORS, FIND_REPLACE_STYLESHEET, MAIN_STYLESHEET, IV_BUTTON_STYLES, ADVANCED_CHECK_STYLES, 
                           RIGHT_WIDGET_STYLES, SIMPLE_VIEW_STYLES, DELETE_ROW_STYLES, HOME_STYLES, NEW_PROJECT_STYLES, WFWF_STYLES, 
                           DEFAULT_GRADIENT, DEFAULT_TEXT_STYLE, TEXT_BOX_STYLE_PANEL_STYLESHEET, PROGRESS_STYLES, get_style_diff)
from assets.styles2 import CHROMESTYLES, MANUALOCR_STYLES, MENU_STYLES